### ISSUE TITLE
replace file.mkv with name of what is being downloaded

### ISSUE THREAD

**Issue by Hemps38** [forkwhilefork/plexChromeExt#1]
Is there anyway to replace default file.mkv with name of the show and / or episode?

**Comment by forkwhilefork** [comment]
Hey I think I answered this elsewhere, but for posterity, the file name is chosen by the downloading client. Plex will send the actual name of the file in the "Content Disposition" header. I usually use wget to download files from the URLs produced by this extension, and I use the `--content-disposition` switch to make it set the downloaded filename to the original filename. Hope that helps!
